//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiseTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvertiseTbl()
        {
            this.userWatchLists = new HashSet<userWatchList>();
        }
    
        public int AdvertiseId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string AdsFilePath { get; set; }
        public string UnitPrice { get; set; }
        public string delFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userWatchList> userWatchLists { get; set; }
    }
}
