//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class makemoneyEntities : DbContext
    {
        public makemoneyEntities()
            : base("name=makemoneyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvertiseTbl> AdvertiseTbls { get; set; }
        public virtual DbSet<CityTbl> CityTbls { get; set; }
        public virtual DbSet<CountryTbl> CountryTbls { get; set; }
        public virtual DbSet<MessageTbl> MessageTbls { get; set; }
        public virtual DbSet<PackagesTbl> PackagesTbls { get; set; }
        public virtual DbSet<PkgPaymentDetailsTbl> PkgPaymentDetailsTbls { get; set; }
        public virtual DbSet<RegistrationTbl> RegistrationTbls { get; set; }
        public virtual DbSet<StateTbl> StateTbls { get; set; }
        public virtual DbSet<userPackage> userPackages { get; set; }
        public virtual DbSet<userWatchList> userWatchLists { get; set; }
        public virtual DbSet<WithdrawTbl> WithdrawTbls { get; set; }
    }
}
