//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackagesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PackagesTbl()
        {
            this.userPackages = new HashSet<userPackage>();
            this.userWatchLists = new HashSet<userWatchList>();
        }
    
        public int packageId { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> validity { get; set; }
        public Nullable<double> peradClick { get; set; }
        public Nullable<double> perdayEarning { get; set; }
        public Nullable<double> referalBonus { get; set; }
        public Nullable<double> minWithdraw { get; set; }
        public string Title { get; set; }
        public Nullable<int> dailyAds { get; set; }
        public string PkgImgPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPackage> userPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userWatchList> userWatchLists { get; set; }
    }
}
