//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PkgPaymentDetailsTbl
    {
        public int PaymentDetailsId { get; set; }
        public string PkgName { get; set; }
        public string ReferId { get; set; }
        public string PaymentMethod { get; set; }
        public string MobileAcountNo { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
    }
}
