//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationTbl()
        {
            this.userPackages = new HashSet<userPackage>();
            this.userWatchLists = new HashSet<userWatchList>();
            this.WithdrawTbls = new HashSet<WithdrawTbl>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string ProfileImgPath { get; set; }
        public string Gender { get; set; }
        public string Perspective { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<bool> IsAgreeTerms { get; set; }
        public Nullable<double> balance { get; set; }
        public string FName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userPackage> userPackages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userWatchList> userWatchLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawTbl> WithdrawTbls { get; set; }
    }
}
