//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawTbl
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public string phoneNo { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string isPaid { get; set; }
        public string reqDate { get; set; }
        public string payDate { get; set; }
    
        public virtual RegistrationTbl RegistrationTbl { get; set; }
    }
}
